variable "github_org" {
  description = "org name or GitHub user (ex: my-org)"
  type        = string
}

variable "github_repo" {
  description = "GitHub repository name (ex: my-repo), without the org"
  type        = string
}

variable "role_name" {
  description = "Name of the IAM Role that GitHub Actions will assume (ex: github-actions-deploy-role)"
  type        = string
  default     = "github-actions-deploy-role"
}

variable "aws_account_id" {
  description = "AWS account ID (12 digits) where the IAM Role will be created (ex: 123456789012)"
  type        = string
}

# ==============================================================================
# Option of workflow set to be rendered
# ==============================================================================
variable "workflow_option" {
  description = <<-EOT
    Which set of workflows to generate in .github/workflows:
      - "simple-deploy"               -> 1 workflow: build + upload S3 + invalidation + check status
      - "deploy-and-rollback"         -> 2 workflows: deploy (with backup in rollback bucket) and rollback (toggle via parameter store)
      - "deploy-rollback-and-restore" -> 2 workflows: deploy (with versioned backup in versions bucket) and rollback-and-restore (toggle or restore specific version via parameter store)
  EOT
  type        = string

  validation {
    condition = contains(
      ["simple-deploy", "deploy-and-rollback", "deploy-rollback-and-restore"],
      var.workflow_option
    )
    error_message = "workflow_option must be \"simple-deploy\", \"deploy-and-rollback\" or \"deploy-rollback-and-restore\"."
  }
}

# ==============================================================================
# S3 Buckets — each with a specific role.
# The same buckets are configured in the IAM policy (read/write/delete permissions).
# ==============================================================================

variable "s3_main_bucket_name" {
  description = "Main bucket that serves the static content (used in all options)"
  type        = string
}

variable "s3_rollback_bucket_name" {
  description = "Bucket that stores a copy of the previous version, used for toggling via parameter store (required in deploy-and-rollback and deploy-rollback-and-restore)"
  type        = string
  default     = null
}

variable "s3_versions_bucket_name" {
  description = "Bucket that stores the .tar.gz packages of each version, named by the commit hash (required only in deploy-rollback-and-restore)"
  type        = string
  default     = null
}

variable "ssm_parameter_arn" {
  description = "Full ARN of the specific Parameter Store parameter that can be written by the GitHub Actions workflow (used in all options)"
  type        = string
}

variable "cloudfront_distribution_arn" {
  description = "Full ARN of the CloudFront distribution that will have invalidation permissions"

  type = string
}

# ==============================================================================
# Variables used to RENDER the GitHub Actions workflows
# ==============================================================================

variable "aws_region" {
  description = "AWS region used in the workflows (ex: us-east-1)"
  type        = string
  default     = "us-east-1"
}

variable "deploy_branch" {
  description = "Branch that triggers the deploy workflow (ex: main)"
  type        = string
  default     = "main"
}

variable "build_command" {
  description = "Build command(s) to be inserted into the workflows (placeholder — adjust for your project's actual commands, ex: npm ci && npm run build)"
  type        = string
  default     = "npm ci && npm run build"
}

variable "build_output_dir" {
  description = "Directory generated by the build that will be uploaded to S3 (ex: ./build, ./dist)"
  type        = string
  default     = "./build"
}

variable "ssm_parameter_name" {
  description = "Name (path) of the parameter in the SSM Parameter Store used as a rollback toggle, ex: /app/config/rollback"
  type        = string
}

variable "cloudfront_distribution_id" {
  description = "CloudFront distribution ID (not the ARN) used in the create-invalidation command in the workflows (ex: E1234567890ABC)"
  type        = string
}

variable "workflows_output_path" {
  description = "Path where the .github/workflows folder will be generated (relative to the root of your Terraform repository/project)"
  type        = string
  default     = "../.github/workflows"
}

variable "generate_workflows" {
  description = "If true, generates the workflow files in .github/workflows via templatefile"
  type        = bool
  default     = true
}
